### PR TITLE
chore: cleanup of Post related components

### PR DESCRIPTION
**Pull request by shelegdmitriy**
This PR introduces a couple of cleanups of Post related components. As a part of this cleanup, I removed defining of `fetchGraphQL` method in order to use `VM.require()` for exact the same method:

```
const { fetchGraphQL } = VM.require("${REPL_ACCOUNT}/widget/Entities.QueryApi.Client");
```

### CODE REVIEW

**Comment by gabehamilton** [comment]
Looking good!

**Comment by shelegdmitriy** [comment]
@charleslavon seems like there is an issue with `IndexFeed` as I mentioned in the description. That's why this PR partirly solves that linked issue. I'm not sure we are planning to spend some time on refactoring the `IndexFeed` component. Maybe it's worth to created a separate task with description and maybe some contributor will take a look at it.

**Comment by charleslavon** [comment]
Thanks for the detail @shelegdmitriy. Yes please create an issue to track whatever delta remains after this PR.   What difference will this PR make?

**Comment by shelegdmitriy** [comment]
> Thanks for the detail @shelegdmitriy. Yes please create an issue to track whatever delta remains after this PR. What difference will this PR make?

Changes the upload limit of posts per page (from 10 to 5)

**Review by charleslavon — APPROVED** [review]
Thanks Dima

**Pull request merged**
