### PR TITLE
887 data availability comparison chart

### PR DESCRIPTION
**Pull request by jackson-harris-iii**
Closes: https://github.com/near/near-discovery/issues/887
Near Org Data Availability Dec 14

### CODE REVIEW

**Review by calebjacob — APPROVED** [review]

**Comment by Ishatt** [comment]
@vanessadespain Tagging you here for reference and incase there is any design work needed.

**Comment by vanessadespain** [comment]
Hi yall! I added a new section of our existing [Figma for this design update](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=2731%3A17196&mode=design&t=Pl51ZbEzj5cZnxgo-1) to the Data Availability page. It sounds like there are two additions to be made: 

1. New stats graphic
2. Batch of logos to the bottom of the page. I'm leveraging the logo component we have on the home page for this.

I've posted my preferred design solution to the thread, pending any pushback or feedback: 
image

**Comment by vanessadespain** [comment]
Added the partner logos we currently have [here](https://drive.google.com/drive/u/0/my-drive)

**Comment by vanessadespain** [comment]
Hi! Derrick from the Near Foundation team has put together a list of updated links for the partner logos on this page. The majority of them point to specific Docs pages that mention NEAR DA:

Caldera
https://docs.caldera.xyz/about/alternative-da

Dymension
https://docs.dymension.xyz/build/adv-guide/roller-adv/da-light-client

Fluent
https://docs.fluentlabs.xyz/learn/introduction/what-is-fluent#app-deployment-models
(This is just a general intro, but they have no specific DA pages or content)

Movement Labs
Movement Docs haven’t cover Near DA yet, only Celestia
`Let's keep this URL as-is until we get different guidance - Vanessa`

StarkNet
https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/

Vistara
https://docs.vistara.dev/rollups/create-a-rollup#get-started
(This is their general DA intro page, but they haven’t include Near DA there yet)

AltLayer
https://docs.altlayer.io/altlayer-documentation/core-features-of-altlayers-in-house-rollup-stack/modular
The link above goes to a general intro. They haven’t include Near DA in the “external integration” section yet, only Celestia and EigenDA.

Optimism
https://docs.optimism.io/builders/chain-operators/hacks/data-availability#overview

Arbitrum
https://docs.arbitrum.io/inside-anytrust#data-availability-servers

**Pull request merged**
