### PR TITLE
feat: add nearcatalog records to improve search ux

### PR DESCRIPTION
**Pull request by shelegdmitriy**
This PR introduces changes for Algoria search. `replica_prod_near-social-feed` includes two indexes:

- `prod_near-social-feed` (production records);
- `test-near-catalog-index` (nearcatalog records);

[loom](https://www.loom.com/share/f59a0a634dd0491da471d8ce3ddc5089?sid=c9c50cde-b0d9-4fde-bf4c-05582bc7f29a) video

Closes https://github.com/near/docs/issues/1941

### CODE REVIEW

**Review by calebjacob — APPROVED** [review]

**Comment by shelegdmitriy** [comment]
Thinking about an improvements according to comments under the loom video, I realized we don't really need a separate tab Near Catalog. As a result, my latest commit makes nearcatalog records to be look like a "app". This should not confuse users. I can record another loom video with demo if it's needed

cc @charleslavon @thisisjoshford @s-n-park

**Comment by charleslavon** [comment]
@shelegdmitriy Nice work. Let's merge and test it out!

**Comment by charleslavon** [comment]
Is the index `test-near-catalog-index_query_suggestions ` no longer needed?

**Comment by shelegdmitriy** [comment]
I'll clean that up in a couple of minutes

**Pull request merged**
