### PR TITLE
Update ExploreWidgets.jsx

### PR DESCRIPTION
**Pull request by AngelBlock**
Default to nearweekapp.near/widget/nearweek-newsletter

### CODE REVIEW

**Comment by AngelBlock** [comment]
@milenakrawczyk I'm not sure if this is the best way to handle this, created PR anyway, but lets discuss further

**Comment by charleslavon** [comment]
@AngelBlock take a look at my last commit. This is to support deploy components across distinct mainnet/testnet contracts as described in this [recently updated doc](https://github.com/near/near-discovery-components#contributing).   If you're currently using a specific testnet account to test nearweekapp components, please add it [here](https://github.com/near/near-discovery-components/pull/124/files#diff-24a201ec7d9862267be6b3c9ed01660d7e73e0e30e0674aae9f31d0c9a028209R7) and [here](https://github.com/near/near-discovery-components/pull/124/files#diff-1655b11169a2ad30a2b15f9bdd3850d9955c0179d2baf3fad982c1b7214559edR7), if not we'll deploy onto our discom-dev.testnet.

**Comment by AngelBlock** [comment]
@charleslavon I will review and revert earlier next week, thanks for sharing.

**Comment by charleslavon** [comment]
Merging so we can preview this on test.near.org

**Pull request merged**
