### PR TITLE
Fix mentions auto complete

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Currently, the '@' autocomplete only works at the end of the sentence. I have updated it to be active whenever '@' is mentioned without any preceding letter within the string.

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
@shelegdmitriy can you please review it. Thanks

**Comment by shelegdmitriy** [comment]
Hey @Megha-Dev-19. Thanks for your contribution. Your solution works but it seems it could be improved even more. Would you mind to take a look at this [solution](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/MainPage.N.Common.Compose)?

**Comment by shelegdmitriy** [comment]
Hey @Megha-Dev-19! I was doing another round of review of your PR. Then I tried this feature on near.org and I don't understand what this PR actually fixes. Autocomplete works fine for me, may I ask you to provide an example like before -> after please?

Sorry for such a long response from side.

**Comment by shelegdmitriy** [comment]
> hey @shelegdmitriy I completely missed your last comment, I m attaching a screencast of the issue
> 
>  Screen.Recording.2024-02-06.at.19.44.15.mov

Ok, I got it!

**Review by shelegdmitriy — CHANGES_REQUESTED** [review]

**Comment by shelegdmitriy** [comment]
Hey @Megha-Dev-19! Are you still interested in resolving the last comment in this PR? Let me know if my comment wasn't clear

**Comment by Megha-Dev-19** [comment]
hey @shelegdmitriy, I got busy with other work, I will make the changes now

**Comment by shelegdmitriy** [comment]
> hey @shelegdmitriy, I got busy with other work, I have made the changes, but haven't tested it out. please let me know if there is an issue

Hey @Megha-Dev-19. After your last commit I'm not able to start a sentence from `@`. Locally, I switched back to your previous commit and everything works fine, may I ask you to check it please?

**Comment by Megha-Dev-19** [comment]
Hey @shelegdmitriy, may I know how do you test it.? By deploying the components.?

**Pull request closed without merging**
