### PR TITLE
feat: Update auto complete widget

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
- show list even when the account is not following anyone
- allow some accounts to be filtered from the displayable list

### CODE REVIEW

**Review by shelegdmitriy — APPROVED** [review]
LGTM! Thanks for your contribution @Megha-Dev-19

**Comment by shelegdmitriy** [comment]
Hey @Megha-Dev-19! May I ask you to pull the latest changes from `develop` and run `pnpm i && pnpm run prettier:write` please? After this steps update this PR. Thanks

**Comment by Megha-Dev-19** [comment]
@shelegdmitriy, done.

**Comment by shelegdmitriy** [comment]
> @shelegdmitriy, done.

Thanks, but there are too many files. It shouldn't be like that

**Comment by Megha-Dev-19** [comment]
yeah the prettier command updated all the files.

**Comment by shelegdmitriy** [comment]
> yeah the prettier command updated all the files.

That's too bad. May I ask you to revert your commit?

**Pull request merged**
