### PR TITLE
Nearcon app quest

### PR DESCRIPTION
**Pull request by roshaans**
We are creating a Near Con APP Quest.

### CODE REVIEW

**Comment by TiffanyGYJ** [comment]
Context: 
We are doing a special NEARCON App Upvoting Event, more details here 
[Google Doc on the event ](https://docs.google.com/document/d/16uQdR0iRcWq8kyBFgUauATdWq7HMPQYMiNZyPnPkG9o/edit?usp=sharing)
[Blog Post with simplified explanation for DApp owners](https://docs.google.com/document/d/1-T1npHHg93ZI6JXZ-z2Z8t4Mm9xV_sLaOE4an_6lLKw/edit?usp=sharing ) 

TLDR: 
- this is a NEARCON Event in the form of a NCON Task that ask people to upvote qualified apps and decide who gets featured 
- We are using a fork of the App Library and populate it with Apps that are qualified (description required + tags<Earn,play,develop,engage> required, so we are running a data filtering pipeline on the back to grab those. 
- Then we will enable a upvote button on the details page of these qualified apps.
- Users at NEARCon can visit this App Upvoting Event component, look at the qualified apps, upvote the ones they like.
- Result is top 8 upvotes will get featured in the App Library (near.org/applications)

**Review by calebjacob — APPROVED** [review]

**Comment by scopalaffairs** [comment]
@calebjacob this has been approved by @TiffanyGYJ regarding copy and layout as well as categorization filtering.
Can this be fast-tracked and deployed by end of day, please?

**Comment by scopalaffairs** [comment]
Upcoming metadata file...

**Review by calebjacob — APPROVED** [review]
Looks good! Nice work.

**Pull request merged**
